version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
